# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "password"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: 'mojo_template'
engines:
    mojo_template:
        auto_escape: 1
        namespace: 'VR::View'
        prepend: 'use Data::Dumper; my $token = $_[0];'
        encoding: 'UTF-8'

plugins:
    Passphrase:
        default: BlowfishCrypt

        SaltedDigest:
            algorithm: 'SHA-256'


    Database:
        driver:   'mysql'
        database: 'testing'
        host:     '127.0.0.1'
        username: 'vegrev'
        password: 'password'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 0
            mysql_enable_utf8: 1
